on:
    push:
        # Only trigger for specific branches or changes in specific paths.
        branches:
            - '*'
        paths:
            - '**'
        # Tag push events should be ignored, they will be handled with the create event below.
        tags-ignore:
            - '*'
    create:
        tags:
            - '*'
    delete:
        tags:
            - '*'

jobs:
    sync_commits:
        runs-on: ubuntu-latest
        name: Sync commits
        if: github.repository == 'Csardelacal/PHPAuthServer' # Execute this workflow job only on the main repository.
        steps:
            -   uses: actions/checkout@v3.3.0
                with:
                    persist-credentials: false
                    fetch-depth: 0

            # Add a personal access token to the repository secrets. This will allow the splitter action to push the new commits
            -   uses: frankdejonge/use-github-token@1.0.1
                with:
                    authentication: 'Csardelacal:${{ secrets.PERSONAL_GITHUB_TOKEN }}'
                    user_name: 'Split Bot'
                    user_email: 'cesar@magic3w.com'

            # Cache the splitsh executable to speedup future runs
            -   name: Cache splitsh-lite
                uses: actions/cache@v4.2.0
                with:
                    path: './splitsh'
                    key: '${{ runner.os }}-splitsh-v101'

            # Sync commits and tags for the configured subtree splits
            -   name: subtree split
                uses: acrobat/subtree-splitter@v1.1.4
                with:
                    config-path: .github/subtree.json # Reference the location where you saved your config file
